-- AlterTable
ALTER TABLE "Anime" ADD COLUMN "endDay" INTEGER;
ALTER TABLE "Anime" ADD COLUMN "endMonth" INTEGER;
ALTER TABLE "Anime" ADD COLUMN "endYear" INTEGER;
ALTER TABLE "Anime" ADD COLUMN "startDay" INTEGER;
ALTER TABLE "Anime" ADD COLUMN "startMonth" INTEGER;
ALTER TABLE "Anime" ADD COLUMN "startYear" INTEGER;
